import assert from 'node:assert/strict';
import {createTerrain} from '../lab/terrain-geometry.js';
import {WEAPONS} from '../lab/terrain-weapons.js';
import {createFieldCombat,pickFocusTarget} from '../lab/field-combat.js';

const terrain=createTerrain({obstacles:[]}),combat=createFieldCombat(terrain,{random:()=>.5});
const user=(weapon='rifle',skill=1)=>({x:50,y:100,id:0,skill,weapon,path:[]});
const enemy=(x=150,y=100)=>({x,y,hp:100});
const u=user(),e=enemy();combat.equip(u);
assert.equal(pickFocusTarget([e],{x:150,y:88},terrain.project,()=>true),e);
assert.equal(pickFocusTarget([e],{x:150,y:88},terrain.project,()=>false),null);
assert.equal(pickFocusTarget([e],{x:300,y:88},terrain.project,()=>true),null);
const direct={point:{x:150,y:88}};
const shot=combat.tick(u,.016,direct,[e]);
assert.equal(shot.length,1);assert.equal(shot[0].victim,e);assert.equal(e.hp,99);
assert.equal(u.gun.ammo,29);
assert.equal(combat.tick(u,.016,direct,[e]).length,0,'held fire respects cadence');
let count=1;for(let i=0;i<90;i++)count+=combat.tick(u,1/60,direct,[e]).length;
assert.ok(count>=12&&count<=14,'held fire repeats at the faster rifle cadence');
const away=enemy(150,180),awayHp=away.hp;
const fresh=user();combat.equip(fresh);combat.tick(fresh,.016,direct,[away]);assert.equal(away.hp,awayHp,'no target snapping');
const front=enemy(110),rear=enemy(160);const first=combat.trace(user(),{x:200,y:100,z:1},0,[rear,front]);
assert.equal(first.victim,front,'first enemy receives the hit');
const wallTerrain=createTerrain({obstacles:[{id:'wall',hit:[100,100,15,30],height:3,name:'wall'}]});
const blocked=createFieldCombat(wallTerrain,{random:()=>.5}),blockedEnemy=enemy();
const wallShot=blocked.trace(user(),{x:200,y:100,z:1},0,[blockedEnemy]);assert.equal(wallShot.victim,null);assert.equal(wallShot.b.id,'wall');
const spread=createFieldCombat(terrain,{random:()=>1}),unskilled=user('rifle',0),accurate=user('beam',1),missTarget=enemy(300);
spread.equip(unskilled);for(let i=0;i<40;i++)spread.tick(unskilled,1/60,{target:missTarget},[]);
assert.equal(spread.tick(unskilled,.3,{target:missTarget},[missTarget])[0]?.victim,null,'poor aim can physically miss');
combat.equip(accurate);assert.equal(combat.tick(accurate,.016,{target:missTarget},[missTarget])[0].victim,missTarget);
const highUser={...user(),x:803,y:230},lowEnemy=enemy(803,400);
combat.equip(highUser);
assert.equal(combat.tick(highUser,.016,{point:{x:803,y:388}},[lowEnemy])[0].victim,lowEnemy,'manual aim projects from highland down to the visible body');
const shotgun=user('shotgun');combat.equip(shotgun);assert.equal(combat.tick(shotgun,.016,direct,[]).length,7);assert.equal(shotgun.gun.ammo,5);
const empty=user('pistol');combat.equip(empty);empty.gun.ammo=1;
combat.tick(empty,.016,direct,[]);assert.ok(empty.gun.reload>0);combat.tick(empty,2,null,[]);
assert.equal(empty.gun.ammo,12);assert.equal(empty.gun.reserve,36);
const battery=user('beam');combat.equip(battery);battery.gun.ammo=1;combat.tick(battery,.016,direct,[]);
assert.ok(battery.gun.reload>WEAPONS.rifle.reload);combat.tick(battery,3,null,[]);
assert.equal(battery.gun.ammo,100);assert.equal(battery.gun.reserve,2);
const exhausted=user('rifle');combat.equip(exhausted);exhausted.gun.ammo=0;exhausted.gun.reserve=0;
assert.equal(combat.tick(exhausted,10,direct,[]).length,0);assert.equal(exhausted.gun.reload,0);
const rangeOnly=user();combat.equip(rangeOnly);
const nearRay=combat.tick(rangeOnly,.016,{point:{x:60,y:79.2}},[])[0];
assert.ok(Math.abs(Math.hypot(nearRay.b.x-nearRay.a.x,nearRay.b.y-nearRay.a.y)-WEAPONS.rifle.range)<.001,'pointer distance does not shorten the shot');
const interrupted=user('beamSniper');combat.equip(interrupted);
combat.tick(interrupted,.2,direct,[]);combat.tick(interrupted,.1,null,[]);
assert.equal(interrupted.gun.charge,0);assert.equal(interrupted.gun.ammo,100,'releasing before charge completes does not fire');
const laser=user('beamSniper'),moving=enemy(220);combat.equip(laser);
for(let i=0;i<29;i++)assert.equal(combat.tick(laser,1/60,{target:moving},[moving]).length,0);
let rays=[];for(let i=0;i<3;i++)rays.push(...combat.tick(laser,1/60,{target:moving},[moving]));assert.ok(rays.length>0);
const beamAmmo=laser.gun.ammo;moving.y=112;const tracked=combat.tick(laser,1/60,null,[moving]);
assert.equal(tracked[0].victim,moving,'active beam tracks its locked target after mouse release');
assert.equal(tracked[0].b.y,moving.y,'tracking beam follows the hit victim without random wobble');
assert.ok(laser.gun.ammo<beamAmmo);
for(let i=0;i<100;i++)combat.tick(laser,1/60,null,[moving]);
assert.equal(laser.gun.channel,0);assert.ok(Math.abs(laser.gun.ammo-50)<.01,'1.25 second channel consumes fifty charge');
combat.cancel(laser);assert.equal(laser.gun.charge,0);
const missLaser=user('beamSniper'),newTarget=enemy(220,180);combat.equip(missLaser);
const missed=combat.tick(missLaser,.5,direct,[newTarget])[0];assert.equal(missed.victim,null);
newTarget.y=100;
const stillMissed=combat.tick(missLaser,.1,{target:newTarget},[newTarget])[0];
assert.equal(stillMissed.victim,null,'a missed channel cannot acquire a target later');
assert.deepEqual(stillMissed.b,missed.b,'missed beam direction stays fixed despite new input');
assert.equal(newTarget.hp,100);
const recoilFree=user('beam',1),beamCombat=createFieldCombat(terrain,{random:()=>1});beamCombat.equip(recoilFree);
recoilFree.moveSpeed=120;
const straight=[];for(let i=0;i<8;i++)straight.push(...beamCombat.tick(recoilFree,.1,direct,[]));
assert.equal(recoilFree.gun.heat,0,'beam rifle does not accumulate recoil');
for(const ray of straight)assert.deepEqual(ray.b,straight[0].b,'moving and repeated beam shots keep the same trajectory');
console.log('PASS: directional hitscan, misses, cadence, first hits, terrain blocking, seven-pellet shotgun, reload/battery, charged tracking beam');
